# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
addons:
      apt_packages:
        - gfortran
  #      - python3-matplotlib
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.add("Ipopt")'
  - julia -e 'Pkg.build("Ipopt")'
  - julia -e 'ENV["PYTHON"]=""'
  - julia -e 'Pkg.build("PyCall")'
  - julia -e 'Pkg.test("PrettyPlots")'

# sudo apt-get install python3-matplotlib
